version: '3.9'

services:
  # ------------------------------
  # MySQL Database
  # ------------------------------
  mysql:
    image: mysql:8.0
    container_name: pm-mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - pm-network

  # ------------------------------
  # Redis Cache
  # ------------------------------
  redis:
    image: redis:6.2
    container_name: pm-redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./redis/data:/data
    networks:
      - pm-network

  # ------------------------------
  # PHP-FPM (ProcessMaker Core)
  # ------------------------------
  php:
    image: processmaker/processmaker:latest
    container_name: pm-php
    restart: always
    volumes:
      - ${PM_VOLUME}:/var/www/html
    environment:
      APP_URL: ${APP_URL}
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      CACHE_DRIVER: redis
      QUEUE_CONNECTION: redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - mysql
      - redis
    networks:
      - pm-network

  # ------------------------------
  # Nginx Web Server
  # ------------------------------
  nginx:
    image: nginx:1.25
    container_name: pm-nginx
    restart: always
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ${PM_VOLUME}:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - pm-network

  # ------------------------------
  # Queue Worker
  # ------------------------------
  worker:
    image: processmaker/processmaker:latest
    container_name: pm-worker
    command: php artisan queue:work
    restart: always
    volumes:
      - ${PM_VOLUME}:/var/www/html
    depends_on:
      - mysql
      - redis
    networks:
      - pm-network

  # ------------------------------
  # Cron Job
  # ------------------------------
  cron:
    image: processmaker/processmaker:latest
    container_name: pm-cron
    command: >
      sh -c "echo '* * * * * cd /var/www/html && php artisan schedule:run >> /dev/null 2>&1' | crontab - && cron -f"
    volumes:
      - ${PM_VOLUME}:/var/www/html
    depends_on:
      - mysql
      - redis
    networks:
      - pm-network

# ------------------------------
# Networks
# ------------------------------
networks:
  pm-network:
    driver: bridge
